#!/usr/bin/env node
import { config } from "../src/config.js";
import { loadNativePostgresStore } from "../src/storePostgresNative.js";

const args = new Set(process.argv.slice(2));
const keepData = args.has("--keep-data");

if (args.has("--help")) {
  console.log([
    "Usage:",
    "  DEE_DATABASE_URL=postgres://... npm run postgres:smoke",
    "  DEE_DATABASE_URL=postgres://... npm run postgres:smoke -- --keep-data",
    "",
    "Runs a live native-Postgres smoke test: schema startup, health probe,",
    "rule draft creation, publish, audit write, client event write, and cleanup."
  ].join("\n"));
  process.exit(0);
}

if (!config.databaseUrl) {
  throw new Error("DEE_DATABASE_URL is required for postgres:smoke.");
}

const runId = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
const decisionKey = `postgres_smoke_${runId}`;
const profileKey = `smoke_profile_${runId}`;
const eventId = `smoke_event_${runId}`;
let store;

try {
  store = await loadNativePostgresStore();
  const health = await store.health();
  assertSmoke(health.ok, `health probe failed: ${health.error || "unknown error"}`);

  const created = await store.createRuleSet(
    {
      decision_key: decisionKey,
      name: "Postgres Smoke Test",
      description: "Temporary rule generated by scripts/postgres-smoke.js.",
      type: "decision",
      priority: 1,
      surface: "smoke",
      input_schema: { attributes: [] },
      output_schema: { result: "string" },
      draft: {
        fallback: {
          result: "eligible",
          outputs: { smoke_run_id: runId }
        },
        branches: []
      },
      tags: ["smoke", "postgres"]
    },
    "postgres-smoke"
  );
  assertSmoke(created.decision_key === decisionKey, "rule creation returned an unexpected decision key.");

  const version = await store.publish(decisionKey, "postgres-smoke");
  assertSmoke(version.version === 1, "publish did not create version 1.");

  await store.addAudit({
    evaluated_at: new Date().toISOString(),
    decision_key: decisionKey,
    profile_key: profileKey,
    rule_version: version.version,
    result: "eligible",
    outputs: { smoke_run_id: runId },
    matched_rules: ["fallback"],
    errors: []
  });

  const event = await store.addClientEvent({
    event_id: eventId,
    event_type: "impression",
    decision_key: decisionKey,
    profile_key: profileKey,
    rule_version: version.version,
    variant_key: "fallback",
    surface: "smoke",
    context: { source: "postgres_smoke" }
  });
  assertSmoke(event.accepted === true, "client event was not accepted.");

  console.log(JSON.stringify({
    ok: true,
    adapter: health.adapter,
    deployment_status: health.deployment?.status,
    pool: health.postgres?.pool || null,
    decision_key: decisionKey,
    rule_version: version.version,
    cleanup: keepData ? "skipped" : "completed"
  }, null, 2));
} finally {
  if (store && !keepData) {
    await cleanupSmokeData(store, { decisionKey, profileKey, eventId }).catch((error) => {
      console.error(`Smoke cleanup failed: ${error.message}`);
    });
  }
  if (store?.close) await store.close();
}

function assertSmoke(condition, message) {
  if (!condition) throw new Error(message);
}

async function cleanupSmokeData(store, { decisionKey, profileKey, eventId }) {
  await store.client.query("DELETE FROM client_events WHERE event_id = $1 OR decision_key = $2", [eventId, decisionKey]);
  await store.client.query("DELETE FROM audit_log WHERE decision_key = $1 OR profile_key = $2", [decisionKey, profileKey]);
  await store.client.query("DELETE FROM rule_sets WHERE decision_key = $1", [decisionKey]);
}
